// Combat backgrounds. Art is generated by tools/art/zones/<id>.ts into
// public/assets/zones/<id>/; this registry holds how the zone behaves at runtime.
// Adding one: see .claude/skills/new-combat-background.
import { FactionId, ZoneDef } from './types';

export const ZONES: ZoneDef[] = [
  {
    id: 'frostfang',
    name: 'Frostfang Ruins',
    subtitle: 'The frozen temple of the broken Oath',
    ambient: 'snow',
    glow: [255, 170, 80],
    shadow: { dx: 1, stretch: 1 },
  },
  {
    id: 'sunscar',
    name: 'Sunscar Ruins',
    subtitle: 'Necropolis of the sun kings',
    ambient: 'sand',
    glow: [255, 150, 60],
    shadow: { dx: 6, stretch: 1.35 },
    tint: { color: '#ff9a50', alpha: 0.08, op: 'soft-light' },
    birds: 3,
    haze: true,
  },
  {
    id: 'nyota',
    name: 'Nyota Skyforge',
    subtitle: 'Terrace of the star-smiths',
    ambient: 'motes',
    glow: [90, 230, 220],
    shadow: { dx: 2, stretch: 1.1 },
    tint: { color: '#7a3cc8', alpha: 0.06, op: 'soft-light' },
    birds: 2,
    embers: ['#90f5e2', '#e8fff8', '#90f5e2', '#36d0c0', '#18908a'],
  },
];

const byId = new Map(ZONES.map((z) => [z.id, z]));

/** The zone a faction calls home: where its champions stand in the Academy demos and their dioramas. */
export function homeZone(faction: FactionId): ZoneDef {
  return zone(faction === 'sunscar' ? 'sunscar' : faction === 'nyota' ? 'nyota' : 'frostfang');
}

export function zone(id: string): ZoneDef {
  const z = byId.get(id);
  if (!z) throw new Error(`unknown zone "${id}"`);
  return z;
}
