// Combat backgrounds. Art is generated by tools/art/zones/<id>.ts into
// public/assets/zones/<id>/; this registry holds how the zone behaves at runtime.
// Adding one: see .claude/skills/new-combat-background.
import { ZoneDef } from './types';

export const ZONES: ZoneDef[] = [
  {
    id: 'frostfang',
    name: 'Frostfang Ruins',
    subtitle: 'The frozen temple of the broken Oath',
    ambient: 'snow',
    glow: [255, 170, 80],
    shadow: { dx: 1, stretch: 1 },
  },
  {
    id: 'sunscar',
    name: 'Sunscar Ruins',
    subtitle: 'Necropolis of the sun kings',
    ambient: 'sand',
    glow: [255, 150, 60],
    shadow: { dx: 6, stretch: 1.35 },
    tint: { color: '#ff9a50', alpha: 0.08, op: 'soft-light' },
    birds: 3,
    haze: true,
  },
];

const byId = new Map(ZONES.map((z) => [z.id, z]));

export function zone(id: string): ZoneDef {
  const z = byId.get(id);
  if (!z) throw new Error(`unknown zone "${id}"`);
  return z;
}
