// Combat backgrounds. Art is generated by tools/art/zones/<id>.ts into
// public/assets/zones/<id>/; this registry holds how the zone behaves at runtime.
// Adding one: see .claude/skills/new-combat-background.
import { FactionId, ZoneDef } from './types';

export const ZONES: ZoneDef[] = [
  {
    // Zone 1 from Jakub's working notes: open sky, a dim island, a small settlement
    id: 'zone1',
    name: 'A Dim Island',
    subtitle: 'Open sky over a small settlement',
    ambient: 'motes',
    glow: [255, 176, 96],
    shadow: { dx: 2, stretch: 1.1 },
    tint: { color: '#3c4a78', alpha: 0.07, op: 'soft-light' },
  },
];

const byId = new Map(ZONES.map((z) => [z.id, z]));

/**
 * The zone a faction calls home: where its champions stand in the Academy
 * demos and on their detail page. No faction has a home yet, so every one
 * stands in the first zone.
 */
export function homeZone(faction: FactionId): ZoneDef {
  void faction;
  return ZONES[0];
}

export function zone(id: string): ZoneDef {
  const z = byId.get(id);
  if (!z) throw new Error(`unknown zone "${id}"`);
  return z;
}
