// Options: battle defaults, the demo shortcut that unlocks everything, and a
// guarded progress reset.
import { W } from '../../engine/screen';
import { App } from '../app';
import { newArchivist, saveArchivist, unlockEverything } from '../archivist';
import { COLORS } from '../ui/ui';
import { BaseScreen, Diorama } from './base';

export class OptionsScreen extends BaseScreen {
  private confirm: 'reset' | 'unlock' | null = null;
  private note = '';
  private diorama: Diorama;

  constructor(app: App) {
    super(app);
    this.diorama = new Diorama(app, 'frostfang');
    this.ui.focusId = 'speed_' + this.archivist.settings.speed;
  }

  protected back() {
    if (this.confirm) this.confirm = null;
    else this.app.router.menu();
  }

  protected update(dt: number) {
    this.diorama.update(dt);
  }

  protected draw(ctx: CanvasRenderingContext2D) {
    const ui = this.ui;
    const p = this.archivist;
    this.diorama.draw(ctx, this.t, 0.72);
    this.header(ctx, 'OPTIONS');
    const w = 380, h = 226, x = Math.round(W / 2 - w / 2), y = 60;
    ui.panel(ctx, 'gold', x, y, w, h);
    let cy = y + 16;
    const label = (text: string, sub: string) => {
      ui.text(ctx, text, x + 16, cy, { color: COLORS.goldHi, variant: 'bold' });
      ui.text(ctx, sub, x + 16, cy + 11, { color: COLORS.faint });
    };

    label('BATTLE SPEED', 'Default for new battles (S in battle).');
    for (const s of [1, 2, 3] as const) {
      ui.button(ctx, 'speed_' + s, x + w - 16 - (4 - s) * 46, cy, 42, 20, `x${s}`, { kind: 'small', active: p.settings.speed === s, click: () => this.set({ speed: s }) });
    }
    cy += 34;
    label('AUTO BATTLE', 'Your champions pick their own skills (A in battle).');
    ui.button(ctx, 'auto_on', x + w - 16 - 88, cy, 42, 20, 'ON', { kind: 'small', active: p.settings.auto, click: () => this.set({ auto: true }) });
    ui.button(ctx, 'auto_off', x + w - 16 - 42, cy, 42, 20, 'OFF', { kind: 'small', active: !p.settings.auto, click: () => this.set({ auto: false }) });
    cy += 34;
    ui.divider(ctx, x + 12, cy, w - 24);
    cy += 14;

    label('UNLOCK EVERYTHING', 'Recruit every champion and open every stage.');
    if (this.confirm === 'unlock') this.confirmRow(ctx, x + w - 16, cy, () => {
      unlockEverything(p);
      this.note = 'Every champion recruited, every stage open.';
    });
    else ui.button(ctx, 'unlock', x + w - 16 - 92, cy, 92, 20, 'UNLOCK', { kind: 'small', click: () => (this.confirm = 'unlock') });
    cy += 34;
    label('RESET PROGRESS', 'Back to the three starters and stage 1-1.');
    if (this.confirm === 'reset') this.confirmRow(ctx, x + w - 16, cy, () => {
      Object.assign(p, newArchivist());
      saveArchivist(p);
      this.note = 'Progress reset.';
    });
    else ui.button(ctx, 'reset', x + w - 16 - 92, cy, 92, 20, 'RESET', { kind: 'small', color: COLORS.bad, click: () => (this.confirm = 'reset') });
    cy += 34;
    ui.divider(ctx, x + 12, cy, w - 24);
    cy += 12;
    if (this.note) ui.text(ctx, this.note, W / 2, cy, { color: COLORS.good, align: 'center' });
    cy += 14;
    ui.para(ctx, 'Every sprite, tile, effect and icon in The Loom is generated by code (tools/art) from one palette and one light. Progress is saved in this browser.', x + 16, cy, w - 32, { color: COLORS.faint });
  }

  private confirmRow(ctx: CanvasRenderingContext2D, right: number, y: number, yes: () => void) {
    const ui = this.ui;
    ui.text(ctx, 'Sure?', right - 140, y + 6, { color: COLORS.bad, variant: 'bold' });
    ui.button(ctx, 'yes', right - 98, y, 46, 20, 'YES', { kind: 'small', click: () => {
      yes();
      this.confirm = null;
    } });
    ui.button(ctx, 'no', right - 46, y, 46, 20, 'NO', { kind: 'small', click: () => (this.confirm = null) });
  }

  private set(s: Partial<App['archivist']['settings']>) {
    this.archivist.settings = { ...this.archivist.settings, ...s };
    this.app.save();
  }
}
